services:
    user.transaction_listener:
        class: StatisticBundle\EventListener\TransactionListener
        arguments: [@doctrine.orm.default_entity_manager]
        tags:
            - { name: kernel.event_listener, event: 'add_transaction', method: 'addTransaction' }
